from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class ChatQueryRequest(BaseModel):
    message: str = Field(..., description="The query message/question from the user")
    conversation_id: Optional[str] = Field(None, description="Optional conversation identifier")

class ChatQueryResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the system")
    sources: List[Dict[str, Any]] = Field(default=[], description="List of source document chunks referenced")
    intent: str = Field(..., description="Identified user intent")

class DocumentIngestRequest(BaseModel):
    title: str = Field(..., description="Title of the documentation")
    content: str = Field(..., description="Raw text content of the document")
    metadata: Optional[Dict[str, Any]] = Field(default={}, description="Optional metadata fields")

class DocumentIngestResponse(BaseModel):
    success: bool
    document_id: str
    chunks_count: int
