RELATIONSHIP_MAP = {
    "VPC": "IN_VPC",
    "SUBNET": "IN_SUBNET",
    "SECURITYGROUP": "USES_SG",
    "SECURITY_GROUP": "USES_SG",
    "SG": "USES_SG",
    "EBS": "ATTACHED_TO",
    "VOLUME": "ATTACHED_TO",
    "IAM": "USES_ROLE",
    "IAM_ROLE": "USES_ROLE",
    "IAMUSER": "USES_ROLE",
    "TARGETGROUP": "TARGETS",
    "LOADBALANCER": "ATTACHED_TO",
    "ALB": "ATTACHED_TO",
    "LAMBDA": "INVOKES",
    "S3": "USES_BUCKET",
    "RDS": "CONNECTS_TO"
}
