RELATIONSHIP_MAP = {
    "VPC": "IN_VPC",
    "SUBNET": "IN_SUBNET",
    "SECURITYGROUP": "USES_SG",
    "SECURITY_GROUP": "USES_SG",
    "SG": "USES_SG",
    "EBS": "ATTACHED_TO",
    "VOLUME": "ATTACHED_TO",
    "IAM": "USES_ROLE",
    "IAM_ROLE": "USES_ROLE",
    "IAMUSER": "USES_ROLE",
    "TARGETGROUP": "TARGETS",
    "LOADBALANCER": "ATTACHED_TO",
    "ALB": "ATTACHED_TO",
    "LAMBDA": "INVOKES",
    "S3": "USES_BUCKET",
    "RDS": "CONNECTS_TO",
    
    # Sprint 1 Networking additions
    "INTERNETGATEWAY": "ROUTES_TO",
    "NATGATEWAY": "ROUTES_TO",
    "ROUTETABLE": "HAS_ROUTE",
    "NETWORKINTERFACE": "ATTACHED_TO",
    "ELASTICIP": "ATTACHED_TO",
    
    # Sprint 5 Compute additions
    "AUTOSCALINGGROUP": "MANAGES",
    "TARGETGROUP": "TARGETS",
    
    # Sprint 6 Database additions
    "RDS": "USES_DATABASE",
    "DYNAMODB": "USES_DATABASE",
    "ELASTICACHE": "USES_CACHE",
    "OPENSEARCH": "USES_SEARCH"
}
